[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["cd api && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd api && python app.py"