[phases.setup]
nixPkgs = ["python3", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "gunicorn -w 4 -k uvicorn.workers.UvicornWorker --chdir api app:app --bind 0.0.0.0:$PORT"
