services:
  - type: web
    name: drmedra-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd api && gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:$PORT"
    plan: free
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: MODEL_ENDPOINT
        value: "https://api.openai.com/v1/chat/completions"
      - key: PORT
        value: "10000"
